steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agendamentos-frontend:$COMMIT_SHA'
      - '--build-arg'
      - 'NUXT_PUBLIC_API_BASE=$_API_BASE'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: ['push', 'gcr.io/$PROJECT_ID/agendamentos-frontend:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'frontend'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'agendamentos-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/agendamentos-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NUXT_PUBLIC_API_BASE=$_API_BASE'

images:
  - 'gcr.io/$PROJECT_ID/agendamentos-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
